/**
 * All Rigths Reserved by Athenaeum Society
 * 2015-
 * Written by Masaki Komatsu
 */

package com.as.springbook.domain;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;
import org.joda.time.DateTime;
import org.springframework.data.domain.Auditable;
import org.springframework.data.jpa.domain.AbstractAuditable;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
 * Audited Component serves as the abstract base class for the
 * business critical entity, in need for the audits.
 * 
 * Derived entity class will have additional audit table
 * auto-generated by the Hibernate Envers.
 * @author komatsu
 *
 */

@MappedSuperclass
@Audited
public abstract class AuditComponent extends BaseComponent implements Auditable<String, Long> {

	@Column(name = "created_by")
    protected String createdBy;

	@Column(name = "created_date")
	@Type(type="org.joda.time.contrib.hibernate.PersistentDateTime")
	@DateTimeFormat(iso=ISO.DATE_TIME)
    protected DateTime createdDate;

	@Column(name = "last_modified_by")
    protected String lastModifiedBy;
	
	@Column(name = "last_modified_date")
	@Type(type="org.joda.time.contrib.hibernate.PersistentDateTime")
	@DateTimeFormat(iso=ISO.DATE_TIME)
    protected DateTime lastModifiedDate;

	@Override
	public boolean isNew() {
		if (id == null) {
			return true;
		} else {
			return false;
		}
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	@Override
	public DateTime getCreatedDate() {
		return this.createdDate;
	}

	@Override
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	@Override
	public DateTime getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	@Override
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Override
	public void setCreatedDate(DateTime createdDate) {
		this.createdDate = createdDate;
	}

	@Override
	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Override
	public void setLastModifiedDate(DateTime lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
