-- MySQL Script generated by MySQL Workbench
-- Tue Jan  6 16:54:58 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`book` ;

CREATE TABLE IF NOT EXISTS `mydb`.`book` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `published_year` YEAR NULL,
  `rating` VARCHAR(45) NULL,
  `category_id` INT NULL,
  `rental_duration` INT NULL,
  `isdn` VARCHAR(20) NOT NULL,
  `inventory_id` INT NOT NULL,
  PRIMARY KEY (`book_id`),
  UNIQUE INDEX `isdn_UNIQUE` (`isdn` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `address_id` INT NOT NULL,
  `address` VARCHAR(255) NULL,
  `street` VARCHAR(45) NULL,
  `town` VARCHAR(20) NULL,
  `city` VARCHAR(20) NULL,
  `prefecture` VARCHAR(20) NULL,
  `postal_code` VARCHAR(20) NULL,
  `phone` VARCHAR(20) NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`staff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `staff_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `address_id` INT NULL,
  `library_id` INT NULL,
  `picture` BLOB NULL,
  `active` TINYINT(1) NULL,
  `username` VARCHAR(45) NULL,
  PRIMARY KEY (`staff_id`),
  INDEX `fk_staff_library1_idx` (`library_id` ASC),
  INDEX `fk_staff_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_staff_library1`
    FOREIGN KEY (`library_id`)
    REFERENCES `mydb`.`library` (`library_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`library`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`library` ;

CREATE TABLE IF NOT EXISTS `mydb`.`library` (
  `library_id` INT NOT NULL,
  `staff_id` INT NULL,
  `address_id` INT NULL,
  PRIMARY KEY (`library_id`),
  INDEX `fk_library_address1_idx` (`address_id` ASC),
  INDEX `fk_library_staff1_idx` (`staff_id` ASC),
  CONSTRAINT `fk_library_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_library_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `mydb`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inventory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inventory` (
  `inventory_id` INT NOT NULL,
  `book_id` INT NULL,
  `library_id` INT NULL,
  `last_update` DATETIME NULL,
  `rental_id` INT NULL,
  PRIMARY KEY (`inventory_id`),
  INDEX `fk_inventory_library1_idx` (`library_id` ASC),
  CONSTRAINT `fk_inventory_book`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `mydb`.`book` (`inventory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventory_library1`
    FOREIGN KEY (`library_id`)
    REFERENCES `mydb`.`library` (`library_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`author` ;

CREATE TABLE IF NOT EXISTS `mydb`.`author` (
  `author_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`author_id`),
  UNIQUE INDEX `fk_name_UNIQUE` (`first_name` ASC, `last_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`book_author_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`book_author_details` ;

CREATE TABLE IF NOT EXISTS `mydb`.`book_author_details` (
  `book_id` INT NOT NULL,
  `author_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`book_id`, `author_id`),
  INDEX `fk_book_author_details_author1_idx` (`author_id` ASC),
  CONSTRAINT `fk_book_author_details_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`author` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_author_details_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `client_id` INT NOT NULL,
  `library_id` INT NOT NULL,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NULL,
  `address_id` INT NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `create_date` DATETIME NULL,
  `last_update` DATETIME NULL,
  PRIMARY KEY (`client_id`),
  INDEX `fk_client_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_client_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rental`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rental` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rental` (
  `rental_id` INT NOT NULL AUTO_INCREMENT,
  `rental_date` DATETIME NOT NULL,
  `inventory_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `return_date` DATETIME NULL,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`rental_id`),
  INDEX `fk_rental_client1_idx` (`client_id` ASC),
  INDEX `fk_rental_staff1_idx` (`staff_id` ASC),
  CONSTRAINT `fk_rental_inventory1`
    FOREIGN KEY (`rental_id`)
    REFERENCES `mydb`.`inventory` (`rental_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rental_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rental_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `mydb`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
