/**
 * All Rigths Reserved by Athenaeum Society
 * 2015-
 * Written by Masaki Komatsu
 */

package com.as.springbook.domain;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;
import org.joda.time.DateTime;
import org.springframework.data.domain.Auditable;
import org.springframework.data.jpa.domain.AbstractAuditable;
import org.springframework.data.jpa.domain.AbstractPersistable;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
 * Audited Component serves as the abstract base class for the
 * business critical entity, in need for the audits.
 * 
 * Derived entity class will have additional audit table
 * auto-generated by the Hibernate Envers.
 * @author komatsu
 *
 */

@MappedSuperclass
public class AuditComponent extends AbstractPersistable<Long> implements Auditable<String, Long> {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "primary_id")
	private Long Id;
	
	@Column(name = "last_modified_date")
	private DateTime lastUpdated;
	
	@Column(name = "last_modified_by")
	private String lastUpdateUser;
	
	@Column(name = "created_date")
	private DateTime created;
	
	@Column(name = "created_by")
	private String createUser;

	public Long getId() {
		return this.Id;
	}

    public String getCreatedBy() {
        return createUser;
    }

    public void setCreatedBy(String createdBy) {
        this.createUser = createdBy;
    }
    
    public DateTime getCreatedDate() {
        return created;
    }

    public void setCreatedDate(DateTime creationDate) {
        this.created = creationDate;
    }

    public String getLastModifiedBy() {
        return lastUpdateUser;
    }
    
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastUpdateUser = lastModifiedBy;
    }

    public DateTime getLastModifiedDate() {
        return lastUpdated;
    }

    public void setLastModifiedDate(DateTime lastModifiedDate) {
        this.lastUpdated = lastModifiedDate;
    }
	
}
