# All Rights Reserved by Athenaeum Society 2015-
# Written by Inotakuya


#spring:
#  datasource:
#   driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:bookLibrary;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: 
#  jpa:
#    hibernate.ddl-auto: update
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/booklibrary
#    username: inotaku
#    password: inotaku

  